version: "3"
services:
  db:
    image: mysql:latest
    container_name: mydb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "howdb"
      MYSQL_ROOT_PASSWORD: "1111"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1111"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci