const IS_VALID_EMAIL = "VALID_EMAIL";
const IS_VALID_PASSWORD = "VALID_PASSWORD";
const LOGIN_EMAIL = "LOGIN_EMAIL";
const LOGIN_PASSWORD = "LOGIN_PASSWORD";
const MESSAGE_EMAIL = "MESSAGE_EMAIL";
const MESSAGE_PASSWORD = "MESSAGE_PASSWORD";
const LOGIN_STATUS = "LOGIN_STATUS";
const REGISTER_ID = "REGISTER_ID";
const REGISTER_PASSWORD = "REGISTER_PASSWORD";
const REGISTER_NICKNAME = "REGISTER_NICKNAME";

module.exports = {IS_VALID_EMAIL, IS_VALID_PASSWORD, LOGIN_EMAIL, LOGIN_PASSWORD, MESSAGE_EMAIL, MESSAGE_PASSWORD, LOGIN_STATUS, REGISTER_ID, REGISTER_PASSWORD, REGISTER_NICKNAME}